---
title: "Parameters for null fields simulation"
output: pdf_document
---
```{r setup, include=FALSE}
# Project: Ghost fields
# Script purpose: Create parameter table
# Code: Anton Olsson Collentine (anton@olssoncollentine.com)


knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

```


```{r}
library(kableExtra)

parameter <- c("num-researchers",
               "num-hyps",
               "non-null-effects",
               "length-memory",
               "power",
               "power2",
               "journal-publication-bias",
               "researcher-publication-bias",
               "memory-curve",
               "alpha")

definition <- c("number of researchers",
                "number of topics",
                "number of true effects",
                "number of own studies considered when deciding if changing topic",
                "power of 1st true effect",
                "power of 2nd true effect",
                "bias against non-significant results at journal level",
                "bias against non-significant results at researcher level",
                "probability to change topic given number of non-significant own results",
                "false positive rate")

values <- c("100",
            "{2, 3}",
            "{0, 1, 2}",
            "5",
            "{0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 1}",
            "0.8",
            "{0, ??}",
            "{0, ??}",
            "{vote-counting, bayesian}",
            "0.05")

dat <- data.frame(parameter, definition, values)

knitr::kable(dat, booktabs = FALSE) %>%
column_spec(3, width = "7em") %>%
row_spec(0, background = "black", color = "white")
```


```{r}

num_hyps <- 3
non_null <- 0:2
varying <- 0:1

a <- expand.grid("hyps" = num_hyps,
            "non_null" = non_null,
            "varying" =  varying)

a <- a[-4,] #remove impossible row
a[-c(1, 4),] #remove row with no non-null, not interesting

#This gives us an unbiased case where we have 4 possibly interesting
#things to run, basically the things I have run previously.

#What happens when we apply publication bias though?
# Is it relevant to apply it in all cases?

#normalized prob is power / sum(powers)

norm_prob <- function(pwer1, pwer_all){
    pwer1 / sum(pwer_all)
}

#0.5 power (rational)
#0.266 chance to switch on average
#0.5 for 0.05 power
# 0.38 for 0.8 pwer

norm_prob(0.8, c(0.5, 0.05, 0.8))
#0.59
norm_prob(0.5, c(0.5, 0.05, 0.8))
#0.37
norm_prob(0.05, c(0.5, 0.05, 0.8))
#0.037

```
